---
title: "p8131_hw7_mp3745"
author: "Matthew Parker"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(nnet)
library(MASS)
library(pscl)
library(nlme)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

#### 1.

Read in the data
```{r}
pitch_df = read_csv("./data/HW7-politeness_data.csv")
```

Provide boxplots to show the relation between gender/attitude and pitch (ignoring diô°€erent scenarios)
```{r}
pitch_df %>% 
  group_by(gender, attitude) %>% 
  ggplot(aes(x = gender, y = frequency, color = attitude)) + 
  geom_boxplot()
```

Fromt the above boxplots, it appears that females tend to have a higher frequency than males. In addition, those with informal attitude may have a slightly higher pitch than those with polite attitude.
